### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by nickboucher** [zhuchen03/FreeLB#15]
It looks like your Comet API key [made its way](https://github.com/zhuchen03/FreeLB/blob/eb2370161037f3b03c5ab1262fb455dc7da4d361/fairseq-RoBERTa/train.py#L28) into your commits; assuming that this was unintentional, it's probably best to revoke the key and update the code to take this as an input.

Cheers!

**Comment by zhuchen03** [comment]
Thank you for the kind reminder! Yes I have invalidated that API key.
