### ISSUE TITLE
'AlbertForSequenceClassification' object has no attribute 'encoder'

### ISSUE THREAD

**Issue by trueto** [zhuchen03/FreeLB#3]
hi, when i used the example from `huggingface-transformers/examples/run_glue_freelb.py`
i met the error as this `'AlbertForSequenceClassification' object has no attribute 'encoder'`
it seems the code 
```                
if isinstance(model, torch.nn.DataParallel):
        embeds_init = model.module.encoder.embeddings.word_embeddings(batch[0])
else:
        embeds_init = model.encoder.embeddings.word_embeddings(batch[0])
```
can not work!

**Comment by zhuchen03** [comment]
Did you run `pip install --editable .` under huggingface-transformers?

**Comment by trueto** [comment]
> Did you run `pip install --editable .` under huggingface-transformers?

thanks for reply, i  have fixed it!
